#!/bin/bash

bus=0
temp="/tmp/brightness"
step=10
signal=8

if [ ! -f $temp ]; then
	current=$(ddcutil --bus $bus getvcp 10 -t)
	current=${current:9}
	current=${current::-4}
	echo $current > $temp
else
	current=$(cat $temp)
fi

if [ $# -eq 1 ]; then
	if [[ "$1" == "up" ]]; then
		new=$((current + step > 100 ? 100 : current + step))
	elif [[ "$1" == "down" ]]; then
		new=$((current - step < 0 ? 0 : current - step))
	elif [[ "$1" == "left" ]]; then
		new=100
	elif [[ "$1" == "right" ]]; then
		new=0
	else
		new=$current
	fi
	if [ "$new" -ne "$current" ]; then
		pkill -f "ddcutil.*setvcp 10"
		echo {\"percentage\":${new}}
		(ddcutil --bus $bus --sleep-multiplier 0 setvcp 10 $new) &
		pkill -RTMIN+$signal waybar
		echo $new > $temp
	fi
else
	echo {\"percentage\":${current}}
fi


